services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Autowire
  Ang3\Component\OdooApiClient\Factory\ApiClientFactory: ~
  Ang3\Bundle\OdooApiBundle\ORM\Factory\CatalogFactory: ~
  Ang3\Bundle\OdooApiBundle\ORM\Factory\ManagerFactory: ~
  Ang3\Bundle\OdooApiBundle\ORM\RecordNormalizer: ~
  Ang3\Bundle\OdooApiBundle\ORM\Mapping\ClassMetadataFactory: ~

  # 
  # DOCTRINE
  # 
  
  Ang3\Bundle\OdooApiBundle\EventListener\DoctrineListener:
    tags:
      - { name: doctrine.event_listener, event: postLoad }

  # 
  # SERIALIZER
  # 

  Ang3\Bundle\OdooApiBundle\ORM\Serializer\Handler\RecordAssociationHandler:
    tags:
      - { name: jms_serializer.handler, type: Ang3\Bundle\OdooApiBundle\ORM\Serializer\Type\SingleAssociation, direction: serialization, format: json, method: serializeSingleAssociationToJson }
      - { name: jms_serializer.handler, type: Ang3\Bundle\OdooApiBundle\ORM\Serializer\Type\SingleAssociation, direction: deserialization, format: json, method: deserializeSingleAssociationFromJson }
      - { name: jms_serializer.handler, type: Ang3\Bundle\OdooApiBundle\ORM\Serializer\Type\MultipleAssociation, direction: serialization, format: json, method: serializeMultipleAssociationToJson }
      - { name: jms_serializer.handler, type: Ang3\Bundle\OdooApiBundle\ORM\Serializer\Type\MultipleAssociation, direction: deserialization, format: json, method: deserializeMultipleAssociationFromJson }
  # 
  # FAKER
  # 
  
  Ang3\Bundle\OdooApiBundle\DataFixtures\Faker\Provider\ModelProvider:
    tags: [ { name: nelmio_alice.faker.provider } ]