services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Autowire
  Ang3\Bundle\OdooApiBundle\ClientRegistry: ~
  Ang3\Component\Odoo\Client\Factory\ApiClientFactory: ~