services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Autowire
  Ang3\Component\OdooApiClient\Factory\ApiClientFactory: ~

  # 
  # Client
  # 

  ang3_odoo_api.factory.api_client_factory:
    alias: Ang3\Component\OdooApiClient\Factory\ApiClientFactory
    public: true

  ang3_odoo_api.default_external_api_client:
    class: Ang3\Component\OdooApiClient\Client\ExternalApiClient
    factory: 'Ang3\Component\OdooApiClient\Factory\ApiClientFactory:createExternalApiClient'
    arguments:
      $parameters: '%ang3_odoo_api.parameters%'
    public: true

  # 
  # ORM
  # 

  Ang3\Bundle\OdooApiBundle\ORM\ModelRegistry:
    arguments:
      $models: '%ang3_odoo_api.models%'
    public: true
  
  Ang3\Bundle\OdooApiBundle\ORM\RecordManager:
    arguments:
      $client: '@ang3_odoo_api.default_external_api_client'
    public: true

  # 
  # DOCTRINE
  # 
  
  Ang3\Bundle\OdooApiBundle\EventListener\DoctrineListener:
    tags:
      - { name: doctrine.event_listener, event: postLoad }

  # 
  # FAKER
  # 
  
  Ang3\Bundle\OdooApiBundle\DataFixtures\Faker\Provider\ModelProvider:
    tags: [ { name: nelmio_alice.faker.provider } ]

  # 
  # LISTENERS AND SUBSCRIBERS
  # 

  Ang3\Bundle\OdooApiBundle\Serializer\Handler\ManyToOneHandler:
    tags:
      - { name: jms_serializer.subscribing_handler }

  Ang3\Bundle\OdooApiBundle\Serializer\Listener\RecordSubscriber:
    tags:
      - { name: jms_serializer.event_subscriber }