services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    Ang3\Bundle\OdooApiBundle\Model\RecordInterface:
        tags: ['ang3_odoo_api.model']

  # Autowire
  Ang3\Component\OdooApiClient\Factory\ApiClientFactory: ~

  # 
  # Client
  # 

  ang3_odoo_api.factory.api_client_factory:
    alias: Ang3\Component\OdooApiClient\Factory\ApiClientFactory
    public: true

  ang3_odoo_api.default_external_api_client:
    class: Ang3\Component\OdooApiClient\Client\ExternalApiClient
    factory: 'Ang3\Component\OdooApiClient\Factory\ApiClientFactory:createExternalApiClient'
    arguments:
      $parameters: '%ang3_odoo_api.parameters%'
    public: true

  # 
  # ORM
  # 
  
  Ang3\Bundle\OdooApiBundle\ORM\ModelRegistry:
    arguments:
      $parameters: '%ang3_odoo_api.models%'
  
  Ang3\Bundle\OdooApiBundle\ORM\RecordManager:
    arguments:
      $client: '@ang3_odoo_api.default_external_api_client'

  # 
  # LISTENERS AND SUBSCRIBERS
  # 

  Ang3\Bundle\OdooApiBundle\Serializer\Handler\ManyToOneHandler:
    tags:
      - { name: jms_serializer.subscribing_handler }

  Ang3\Bundle\OdooApiBundle\Serializer\Listener\RecordSubscriber:
    tags:
      - { name: jms_serializer.event_subscriber, event: serializer.post_deserialize }