services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Autowire
  Ang3\Component\OdooApiClient\Factory\ApiClientFactory: ~
  Ang3\Bundle\OdooApiBundle\ORM\RecordNormalizer: ~

  # 
  # Client
  # 

  # ang3_odoo_api.factory.api_client_factory:
  #   alias: Ang3\Component\OdooApiClient\Factory\ApiClientFactory
  #   public: true

  # ang3_odoo_api.default_external_api_client:
  #   class: Ang3\Component\OdooApiClient\Client\ExternalApiClient
  #   factory: 'Ang3\Component\OdooApiClient\Factory\ApiClientFactory:createExternalApiClient'
  #   arguments:
  #     $parameters: '%ang3_odoo_api.parameters%'
  #   public: true

  # 
  # DOCTRINE
  # 
  
  Ang3\Bundle\OdooApiBundle\EventListener\DoctrineListener:
    tags:
      - { name: doctrine.event_listener, event: postLoad }

  # 
  # LISTENERS AND SUBSCRIBERS
  # 

  Ang3\Bundle\OdooApiBundle\Serializer\Handler\ManyToOneHandler:
    tags:
      - { name: jms_serializer.subscribing_handler }

  Ang3\Bundle\OdooApiBundle\Serializer\Handler\ManyToManyHandler:
    tags:
      - { name: jms_serializer.subscribing_handler }

  # 
  # FAKER
  # 
  
  Ang3\Bundle\OdooApiBundle\DataFixtures\Faker\Provider\ModelProvider:
    tags: [ { name: nelmio_alice.faker.provider } ]